server:
  port: 8081
  shutdown: graceful

spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION:mongodb://localhost:27017}
      database: ${MONGODB_CONNECTION_NAME:Order}
  mongodb:
    embedded:
      version: 5.0.5

api:
  item-service: http://localhost:8080