name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and publish results
        env:
          PACT_BROKER_BASE_URL: ${{secrets.ENV_PACT_BROKER_BASE_URL}}
          PACT_BROKER_TOKEN: ${{secrets.ENV_PACT_BROKER_TOKEN}}
        run: make build